defaults:
  - submitit_slurm

mem_gb: 300
gres: gpu:h100:1
array_parallelism: 32
tasks_per_node: 1
cpus_per_task: 6
timeout_min: 360
account: rrg-bengioy-ad
additional_parameters:
  no-requeue: true

setup:
  - "source $SCRATCH/nemo-rl/.venv/bin/activate"